name: Validate CSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate CSL file
      uses: citation-style-language/csl-validator@v1
      with:
        file: JJAT_CSL.csl
        
    - name: Test CSL rendering
      run: |
        echo "CSL validation completed successfully!" 